# SEO & Browser Tab Title
title: "Jonas Gil | Computer Graphics & Software Engineering"
description: "Software Engineer specializing in Game Development, Computer Graphics, and Software Localization (Trilingual: ES/EN/ZH)."
url: "https://jonG312.github.io"
baseurl: ""

# Profile information
yourname: "Jonas Gil"
job_title: "COMPUTER GRAPHICS & SOFTWARE ENGINEERING"
location: "Valencia, VZLA"

# Social Profiles
facebook: "https://www.facebook.com/CONSTRUYOU" 
twitter: "https://twitter.com/JONASGI34269219" 
linkedin: "https://www.linkedin.com/in/gildevlink/?locale=en_US"
github: "https://github.com/jonG312"

# Keywords
keywords: "Software Engineering, Game Development, Unity, Unreal Engine, LQA, Software Localization, Trilingual Developer, Computer Graphics"