
title: My Resume
url: 'https://jong312.github.io/'
baseurl: '/jonG312.github.io' #change it according to your repository name



# Profile information
yourname: Jonas Gil  ## put your name
title: 'GRAPHIC COMPUTER &amp; SOFTWARE ENGINEERING'  ## your title
location: Beijing , BJ


## Social Profiles
facebook: https://www.facebook.com/CONSTRUYOU  ## your facebook account url
twitter: https://twitter.com/JONASGI34269219  ## your twitter account url
linkedin: https://www.linkedin.com/in/gildevlink/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
